# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20170926_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='host_machine',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AddField(
            model_name='connector',
            name='io_timeout',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_location',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
