# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-05 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20171101_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='conn_timeout',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='connector',
            name='io_timeout',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='connector',
            name='ip_address',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='connector',
            name='port',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='connector',
            name='sync_to_rt',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='connector',
            name='ts',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
