# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_machine_simulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='machine',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='project',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
