# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('conn_timeout', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DataStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_type', models.CharField(max_length=30)),
                ('host', models.CharField(max_length=25)),
                ('port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('host_machine', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.FloatField()),
                ('progress', models.FloatField()),
                ('status', models.CharField(max_length=15)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Project')),
            ],
        ),
        migrations.AddField(
            model_name='datastream',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Project'),
        ),
        migrations.AddField(
            model_name='connector',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Project'),
        ),
    ]
