# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastream',
            name='project',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='project',
        ),
        migrations.AddField(
            model_name='connector',
            name='from_simulation',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20, null=True), max_length=250, null=True, size=10),
        ),
        migrations.AddField(
            model_name='connector',
            name='host_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='connector',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='connector',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='connector',
            name='sync_to_rt',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='connector',
            name='to_simulation',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20, null=True), max_length=250, null=True, size=10),
        ),
        migrations.AddField(
            model_name='connector',
            name='ts',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='connector',
            name='conn_timeout',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='connector',
            name='port',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='host_machine',
            field=models.URLField(),
        ),
        migrations.DeleteModel(
            name='DataStream',
        ),
        migrations.DeleteModel(
            name='Simulation',
        ),
    ]
